name: CI Python and Javacript

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    
jobs:
    linting_flake:
        name: linting python
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.1.1
            - name: Set up Python 3.12.2
              uses: actions/setup-python@v5
              with:
                python-version: "3.12.2"
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - name: Lint with flake8
              run: |
                flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    linting_eslint:
      name: linting javascript
      needs: linting_flake
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4.1.1
        - name: Setup node
          uses: actions/setup-node@v4.0.2
          with:
            node-version: 20.11.1
        - name: Install dependencies
          run: npm ci
        - name: Lint with ESlint
          run: npx eslint . --ext .js,.jsx,.ts,.tsx

    tesing:
      name: testing
      needs: linting_eslint
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v4.1.1
          - name: Set up Python 3.12.2
            uses: actions/setup-python@v5
            with:
              python-version: "3.12.2"
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
              if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
          - name: Test with pytest
            run: |
              pytest
        
        
