name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            -main
    
jobs:
    setup_python:
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v4.1.1
            - name: Set up Python 3.12.2
              uses: actions/setup-python@v5
              with:
                python-version: "3.12.2"
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi''
    link_flake8:
        needs: setup_python
        runs-on: ubuntu-latest
        steps:
            - name: Lint with flake8
              run: |
                flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

        
        